void InsertionSort(std::vector<int> &);
void SelectionSort(std::vector<int> &);
void HeapSort(std::vector<int> &, int);
void Heap(std::vector<int> &, int, int);
void MergeSort(std::vector<int> &, int, int);
void Merge(std::vector<int> &, int, int, int);
void QuickSort(std::vector<int> &, int, int);
int QuickSortPartition(std::vector<int> &, int, int);
void RadixSort(std::vector<int> &);
void BucketSort(std::vector<int> &);
